import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" class="scroll-smooth">
      <body className={inter.className}>
        <Navbar />
        <div className=" lg:py-16 lg:px-[180px] p-4">{children}</div>
      </body>
    </html>
  );
}
